//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLRUN_INSTRUCTION
    {
        public BILLRUN_INSTRUCTION()
        {
            this.BILLRUN_INSTRUCTION_VALUE = new HashSet<BILLRUN_INSTRUCTION_VALUE>();
        }
    
        public string INSTRUCTIONID { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETED { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public string USERID { get; set; }
    
        public virtual ICollection<BILLRUN_INSTRUCTION_VALUE> BILLRUN_INSTRUCTION_VALUE { get; set; }
    }
}
