//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLRUN_INSTRUCTION_VALUE
    {
        public string INSTRUCTION_VALUEID { get; set; }
        public string INSTRUCTIONID { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
    
        public virtual BILLRUN_INSTRUCTION BILLRUN_INSTRUCTION { get; set; }
    }
}
