//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIDNUMBERINVENTORY
    {
        public int I_DID_NUMBER { get; set; }
        public string PHONENUMBER { get; set; }
        public Nullable<int> I_ACCOUNT { get; set; }
        public Nullable<System.DateTime> RESERVED { get; set; }
        public Nullable<System.DateTime> ASSIGNED { get; set; }
        public Nullable<System.DateTime> RELEASED { get; set; }
        public Nullable<int> I_DV_BATCH { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public string BILL_STATUS { get; set; }
        public short ENVIROMENT { get; set; }
        public Nullable<short> ACCOUNT_ENVIROMENT { get; set; }
    }
}
