//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class voice_job
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string parameters { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
