//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOUD
    {
        public decimal CLOUDID { get; set; }
        public Nullable<decimal> NETWORKID { get; set; }
        public string NAME { get; set; }
        public decimal TIMEZONEMIN { get; set; }
    }
}
