//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class consolidated_itemised_billing
    {
        public string id { get; set; }
        public string customer_id { get; set; }
        public string file_name { get; set; }
        public string billrun_id { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public byte[] file { get; set; }
        public Nullable<bool> calls_in_out { get; set; }
    }
}
