//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagine.Rest.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrEntity : DbContext
    {
        public DrEntity()
            : base("name=DrEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLOUD> CLOUDs { get; set; }
        public DbSet<FLAG> FLAGs { get; set; }
        public DbSet<BILLRUN> BILLRUNs { get; set; }
        public DbSet<BILLRUN_INSTRUCTION> BILLRUN_INSTRUCTION { get; set; }
        public DbSet<BILLRUN_INSTRUCTION_VALUE> BILLRUN_INSTRUCTION_VALUE { get; set; }
    }
}
